def way0(name):
    input("YOU: It's okay, I got it.")
    input("Rachel fades into the darkness and you are left alone.")
    input("Moments later, you hear a scream.")
    input("What happened, you think.")
    input("Your vision is fading.")
    input("You are plunged into absolute darkness.")
    input("Your head falls to the ground, and you are asleep.")
    input("CHAPTER ONE, SCENE 2, OPTION 1")
    input("You wake up, totally blinded.")
    input("You hear a garbled voice beside you, and you can make out some words.")
    input("???: #### " + name.upper() + " ### ## ### LYSERGIC ACID DIETHYLAMIDE ##")
    input("You assume the voice's name is " + name + '.')
    input(name.upper() + ": ## NO HELP #### I GIVE ##### ## #### DEATH ####")
    input("At the mention of death, you sit up quickly, banging your head on the top of what seems to be a box.")
    input(name.upper() + ": DO ### STAND, ###GEROUS")
    input("You are able to make out more.")
    input("YOU: I- I can here you better. Is your name '" + name + "'?")
    input("A needle thrusts into your arm.")
    input(name.upper() + ": #### ### ### ### ##### # ### ####")
    input(name.upper() + ": WEARING ### ### # #### ####")
    input(name.upper() + ": TWENTY #")
    input("YOU: What??")
    input(name.upper() + ": ONE ###")
    input(name.upper() + ": DAYS #")
    input("DAY O1")
    input(name + " comes in. You are able to see clearly now, but you aren't sure about your hearing.")
    input(
        name + " is dressed in a lab coat and has a mask on. You are unable to see " + name + "'s face, but you can tell it's him. No other doctor has come in.")
    input(name.upper() + ": ######## SHIPMENT CO###G. ##ST WAI#.")
def way1(name):
    input("YOU: Um, I guess you shouldn't...")
    input("RACHEL: Okay, I'll make a fire. It'll be a while before you recover.")
    input("You huddle around the fire, you and Rachel across from each other.")
    input("You fall asleep, trusting the safety of the fire.")
    input("CHAPTER 1, SCENE 2, OPTION 2")
    input("Your eyes flutter open, only to see two almost identical eyes.")
    input("You scurry back, tripping on a log.")
    input("Rachel's lifeless eyes are still staring down at where you were sleeping.")
    input("*shink*")
    input("A dagger pulls back out of Rachel's back.")
    input("Her lifeless body falls to the ground, crunching the autumn leaves.")
    input("If the leaves were still green, they would be stained with crimson.")
    input("A white figure beside her turns its head towards you.")
    input("Fear pulses through your body, paralyzing you for what seems like an hour.")
    input("It takes a step towards you, and moves its hand towards its head.")
    input("It tears off what seems to be a mask, revealing a face of sheer muscle.")
    input("It's mouth twists into a terrifying smile.")
    input("???: HELLO, FRIEND.")
    input("YOU: Wh- what the fuck are you?")
    input("???: SHE WASN'T WORTHY. ELIMINATED.")
    input("???: YOU WORTHY?")
    input("???: YOU HAVE THREE WEEKS. IF I CATCH YOU, YOU LOSE.")
    input("???: I LIKE HIDE AND SEEK.")
    input("YOU: The fuck? I'm not doing shit, you hear me?")
    input("???: YOU HAVE TWENTY ONE DAYS.")
    input("DAY 01")
    input("The figure disappears into the night.")
    input("YOU: Is anyone out there?")
    input("Your question echoes through the forest, scaring some birds.")
    input("You wait a moment, and your question stays unanswered.")
    input("You have a choice: You can go into the CITY, or you can walk back to the SUBURBS.")
    direction = response = input("Which way will you go?")
    return direction