def part1():
	input("RACHEL: That party was SOO crazy, man.")
	input("RACHEL: I'm gonna go home. You look pretty delirious. I'm not sure, but I think you might have had something.")
	input("RACHEL: Alright, let's see... hm... how delirious ARE you?")
	input("...")
	input("RACHEL: Oh! I know, can you remember your name?")

def part2(name):
	input("At least you're not totally oblivious. Still, " + name + ", you should let me walk you home.")
	input("The soles of your sneakers scrape against the sidewalk, making noticeable squeaks against the silent background of the suburbs.")
	input("Rachel guides you towards the forest.")
	input("You try to struggle, knowing that it's dangerous.")
	input("You remember campfire stories about this forest.")
	input("Your tripping mind amplifies these memories, as if you were there.")
	input("You see faces flash before you.")
	input("It's as if you are in a first person horror movie.")
	input("RACHEL: Are you okay? You look scared.")
	input("RACHEL: It's ok, I'll stay with you the whole time. You don't have to be scared.")
	input("YOU: It's okay, you go on. I'll catch up with you.")
	input("RACHEL: But you don't even know the way through!")
